FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build
ENTRYPOINT /tools/monitor
RUN mkdir /tools && dotnet tool install --tool-path /tools dotnet-counters
ENV PATH="/tools:${PATH}"
RUN echo -e '#!/bin/bash\ndotnet-counters monitor --name rinhaback2401 --showDeltas --counters Rinha,System.Runtime,Microsoft.AspNetCore.Hosting,Microsoft-AspNetCore-Server-Kestrel' > /tools/monitor && chmod +x /tools/monitor

